### ISSUE TITLE
Errors when trying to run random-beacon for the first time

### ISSUE THREAD

**Issue by quantumgravity444** [dfinity/random-beacon#1]
I followed the guide perfectly. There is no problem with my docker set up or my Ethereum set up since I have both installed already. I added the two 'export' lines into my terminal as written.

After I successfully downloaded and extracted the dfinity/build-env, I then ran docker as specified with success. 

Then I entered the command, "go run main.go" as instructed and received this error:
`# dfinity/beacon/bls
bls/rand.go:68: undefined: common.Bytes2Big`

Any suggestions?

**Comment by timohanke** [comment]
Hi Gregory. What's the hash of your docker image? (dfinity/build-env)

Your Ethereum setup on your host should not matter.

**Comment by timohanke** [comment]
It seems like commit 6636bbb9c926cc22cdb1fec37ac13712e165098f (though old, from March 3) had fixed this but somehow wasn't in the repo. Please try now with a fresh pull.

**Comment by quantumgravity444** [comment]
That did the trick. Thanks!
